package org.com.miaoshaproject.dao;

import org.com.miaoshaproject.dataobject.UserTextDO;
import org.com.miaoshaproject.dataobject.UserTextDOKey;
import org.com.miaoshaproject.dataobject.userImageDO;

import java.util.List;

public interface UserTextDOMapper {

    List<UserTextDO> listText(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    int deleteByPrimaryKey(UserTextDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    int insert(UserTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    int insertSelective(UserTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    UserTextDO selectByPrimaryKey(UserTextDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    int updateByPrimaryKeySelective(UserTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_text
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    int updateByPrimaryKey(UserTextDO record);
}