package org.com.miaoshaproject.dao;

import org.com.miaoshaproject.dataobject.UserAudioDO;
import org.com.miaoshaproject.dataobject.UserVideoDO;
import org.com.miaoshaproject.dataobject.UserVideoDOKey;

import java.util.List;

public interface UserVideoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    List<UserVideoDO> listVideo(Integer key);

    int deleteByPrimaryKey(UserVideoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    int insert(UserVideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    int insertSelective(UserVideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    UserVideoDO selectByPrimaryKey(UserVideoDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    int updateByPrimaryKeySelective(UserVideoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    int updateByPrimaryKey(UserVideoDO record);
}