package org.com.miaoshaproject.dao;

import org.com.miaoshaproject.dataobject.userImageDO;
import org.com.miaoshaproject.dataobject.userImageDOKey;

import java.util.List;

public interface userImageDOMapper {
    /**
     * This method was generated by programmer.
     * This method corresponds to the database table user_image
     *
     *
     */
    List<userImageDO> listImage(Integer key);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    int deleteByPrimaryKey(userImageDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    int insert(userImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    int insertSelective(userImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    userImageDO selectByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    int updateByPrimaryKeySelective(userImageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    int updateByPrimaryKey(userImageDO record);
}