package org.com.miaoshaproject.dao;

import org.com.miaoshaproject.dataobject.UserAudioDO;
import org.com.miaoshaproject.dataobject.UserAudioDOKey;
import org.com.miaoshaproject.dataobject.userImageDO;

import java.util.List;

public interface UserAudioDOMapper {

    List<UserAudioDO> listAudio(Integer key);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    int deleteByPrimaryKey(UserAudioDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    int insert(UserAudioDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    int insertSelective(UserAudioDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    UserAudioDO selectByPrimaryKey(UserAudioDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    int updateByPrimaryKeySelective(UserAudioDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    int updateByPrimaryKey(UserAudioDO record);
}