package org.com.miaoshaproject.dataobject;

public class UserVideoDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.video_id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private Integer videoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.id
     *
     * @return the value of user_video.id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.id
     *
     * @param id the value for user_video.id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.video_id
     *
     * @return the value of user_video.video_id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.video_id
     *
     * @param videoId the value for user_video.video_id
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
}