package org.com.miaoshaproject.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.telphone
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.register_mode
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private String registerMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.third_party_id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer thirdPartyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.image_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer imageNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.video_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer videoNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.audio_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer audioNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.text_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    private Integer textNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.telphone
     *
     * @return the value of user_info.telphone
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.telphone
     *
     * @param telphone the value for user_info.telphone
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.register_mode
     *
     * @return the value of user_info.register_mode
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.register_mode
     *
     * @param registerMode the value for user_info.register_mode
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.third_party_id
     *
     * @return the value of user_info.third_party_id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getThirdPartyId() {
        return thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.third_party_id
     *
     * @param thirdPartyId the value for user_info.third_party_id
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setThirdPartyId(Integer thirdPartyId) {
        this.thirdPartyId = thirdPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.image_num
     *
     * @return the value of user_info.image_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getImageNum() {
        return imageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.image_num
     *
     * @param imageNum the value for user_info.image_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setImageNum(Integer imageNum) {
        this.imageNum = imageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.video_num
     *
     * @return the value of user_info.video_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getVideoNum() {
        return videoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.video_num
     *
     * @param videoNum the value for user_info.video_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setVideoNum(Integer videoNum) {
        this.videoNum = videoNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.audio_num
     *
     * @return the value of user_info.audio_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getAudioNum() {
        return audioNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.audio_num
     *
     * @param audioNum the value for user_info.audio_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setAudioNum(Integer audioNum) {
        this.audioNum = audioNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.text_num
     *
     * @return the value of user_info.text_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public Integer getTextNum() {
        return textNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.text_num
     *
     * @param textNum the value for user_info.text_num
     *
     * @mbg.generated Mon Jun 22 20:15:22 EDT 2020
     */
    public void setTextNum(Integer textNum) {
        this.textNum = textNum;
    }
}