package org.com.miaoshaproject.dataobject;

public class UserAudioDO extends UserAudioDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private String audio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.name
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.type
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.time
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.audio
     *
     * @return the value of user_audio.audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.audio
     *
     * @param audio the value for user_audio.audio
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setAudio(String audio) {
        this.audio = audio == null ? null : audio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.name
     *
     * @return the value of user_audio.name
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.name
     *
     * @param name the value for user_audio.name
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.type
     *
     * @return the value of user_audio.type
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.type
     *
     * @param type the value for user_audio.type
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.time
     *
     * @return the value of user_audio.time
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.time
     *
     * @param time the value for user_audio.time
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}