package org.com.miaoshaproject.dataobject;

public class UserTextDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_text.id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_text.text_id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    private Integer textId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_text.id
     *
     * @return the value of user_text.id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_text.id
     *
     * @param id the value for user_text.id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_text.text_id
     *
     * @return the value of user_text.text_id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    public Integer getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_text.text_id
     *
     * @param textId the value for user_text.text_id
     *
     * @mbg.generated Mon Jun 22 20:22:52 EDT 2020
     */
    public void setTextId(Integer textId) {
        this.textId = textId;
    }
}