package org.com.miaoshaproject.dataobject;

public class userImageDO extends userImageDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_image.image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_image.name
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_image.type
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_image.image
     *
     * @return the value of user_image.image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_image.image
     *
     * @param image the value for user_image.image
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_image.name
     *
     * @return the value of user_image.name
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_image.name
     *
     * @param name the value for user_image.name
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_image.type
     *
     * @return the value of user_image.type
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_image.type
     *
     * @param type the value for user_image.type
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}