package org.com.miaoshaproject.dataobject;

public class UserAudioDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_audio.audio_id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    private Integer audioId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.id
     *
     * @return the value of user_audio.id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.id
     *
     * @param id the value for user_audio.id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_audio.audio_id
     *
     * @return the value of user_audio.audio_id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public Integer getAudioId() {
        return audioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_audio.audio_id
     *
     * @param audioId the value for user_audio.audio_id
     *
     * @mbg.generated Mon Jun 15 16:28:23 EDT 2020
     */
    public void setAudioId(Integer audioId) {
        this.audioId = audioId;
    }
}