package org.com.miaoshaproject.dataobject;

public class UserVideoDO extends UserVideoDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.name
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.type
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_video.time
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.video
     *
     * @return the value of user_video.video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.video
     *
     * @param video the value for user_video.video
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.name
     *
     * @return the value of user_video.name
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.name
     *
     * @param name the value for user_video.name
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.type
     *
     * @return the value of user_video.type
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.type
     *
     * @param type the value for user_video.type
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_video.time
     *
     * @return the value of user_video.time
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_video.time
     *
     * @param time the value for user_video.time
     *
     * @mbg.generated Tue Jun 16 12:02:37 EDT 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}