package org.com.miaoshaproject.dataobject;

public class userImageDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_image.id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_image.image_id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    private Integer imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_image.id
     *
     * @return the value of user_image.id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_image.id
     *
     * @param id the value for user_image.id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_image.image_id
     *
     * @return the value of user_image.image_id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_image.image_id
     *
     * @param imageId the value for user_image.image_id
     *
     * @mbg.generated Tue Jun 09 22:44:50 EDT 2020
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
}